### ISSUE TITLE
Please consider not defaulting to Module::Build

### ISSUE THREAD

**Issue by karenetheridge** [yanick/Dist-Zilla-PluginBundle-YANICK#3]
Please default to [MakeMaker] or [ModuleBuildTiny] in your bundle - it is best if MB is only used when absolutely needed (and even then, the Perl-Toolchain-Gang would appreciate hearing about your usecase so EUMM can be further improved).

**Comment by yanick** [comment]
I relented and began to push releases with MM instead of M::B. :-)

**Comment by karenetheridge** [comment]
\o/
